[package]
name = "themelio-core"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

[workspace] 

[dependencies]
autosmt={path="libs/autosmt"}
blkstructs={path="libs/blkstructs"}
tmelcrypt={path="libs/tmelcrypt"}
melpow={path="libs/melpow"}
symphonia={path="libs/symphonia"}
melnet={path="libs/melnet"}
hex="0.4.2"
futures="0.3"
smol="0.4"
colored="2"
anyhow="1"
tabwriter="1"
env_logger="0.7"
rustyline="6"
log="0.4"
attohttpc={version = "0.15", default-features = false, features=[]}
clap="2"
parking_lot="0.11"
rand="0.7"
lru="0.5"
scopeguard="1.1"
lmdb="0.8"
derive_more="0.99"
defmac="0.2"
structopt="0.3"
rlp="0.4"
rlp-derive="0.1"
async-net="1"
im="15"


[profile.dev]
#panic = "abort"

[profile.release]
panic = "abort"
opt-level = 'z'
#lto = true