[workspace] 

members = [
    "commands/themelio-bxms",
    "commands/themelio-client",
    "commands/themelio-node",

    "libs/autosmt",
    "libs/blkstructs",
        "libs/nodeprot",
    "libs/melnet",
    "libs/melpow",
    "libs/neosymph",
    "libs/stdcode",
    "libs/symphonia",
    "libs/tmelcrypt"
]

[profile.dev]
panic = "abort"
opt-level = 0 

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"